#include <U8g2lib.h>

#if ATOMOLED_TYPE == 1 // TALL
#define ATOMOLED_SCL 25
#define ATOMOLED_SDA 21
#define ATOMOLED_ORIENTATION U8G2_R2
#endif

#if ATOMOLED_TYPE == 2 // SQUARE1
#define ATOMOLED_SCL 22
#define ATOMOLED_SDA 23
#define ATOMOLED_ORIENTATION U8G2_R0
#endif

#if ATOMOLED_TYPE == 3 // SQUARE2, uses GPIO pins for VCC and GND
#define ATOMOLED_SCL 19
#define ATOMOLED_SDA 22
#define ATOMOLED_ORIENTATION U8G2_R2
#endif

#if ATOMOLED_TYPE == 4 // RFID-BOX
#define ATOMOLED_SCL 22
#define ATOMOLED_SDA 19
#define ATOMOLED_ORIENTATION U8G2_R0
#endif

// Instance U8G2
U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(ATOMOLED_ORIENTATION, /* reset=*/U8X8_PIN_NONE, ATOMOLED_SCL, ATOMOLED_SDA); // ESP32 Thing, HW I2C with pin remapping
